[tool.poetry]
name = "graph-demo"
version = "0.1.0"
description = ""
authors = ["frederl <frederic.lhote@statnett.no>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
matplotlib = "^3.10.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
